services:
  backend:
    image: ursaminor5/bobapp-back:fc3f38d
    container_name: bobapp-back
    restart: unless-stopped
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - bobapp_private
  frontend:
    image: ursaminor5/bobapp-front:fc3f38d
    container_name: bobapp-front
    restart: unless-stopped
    ports:
      - "8088:80"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    networks:
      - bobapp_private
      - bobapp_public

networks:
  bobapp_private:
    internal: true
  bobapp_public:
