name: SonarCloud - Back & Front

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  sonar-back:
    name: backend
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Compile and execute tests
        working-directory: back
        run: mvn clean verify

      - name: SonarCloud analyse backend
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: back
          args: >
            -Dsonar.projectKey=jceintrey_gerez-un-projet-collaboratif-back
            -Dsonar.organization=jceintrey
            -Dsonar.sources=src/main/java
            -Dsonar.tests=src/test/java
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.exclusions=**/test/**,**/__mocks__/**
            -Dsonar.sourceEncoding=UTF-8

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
  sonar-front:
    name: frontend
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install & test frontend
        working-directory: front
        run: |
          npm ci
          npm run test -- --watch=false --browsers=CIChrome --code-coverage

      - name: Analyse SonarCloud frontend
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: front

          args: >
            -Dsonar.projectKey=jceintrey_gerez-un-projet-collaboratif-front
            -Dsonar.organization=jceintrey
            -Dsonar.sources=src
            -Dsonar.exclusions=**/node_modules/**,**/*.spec.ts,**/test/**,**/__mocks__/**
            -Dsonar.javascript.lcov.reportPaths=coverage/bobapp/lcov.info
            -Dsonar.sourceEncoding=UTF-8

        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
