name: SonarCloud - Back & Front

on: push

jobs:
  sonar-back:
    name: backend
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "11"

      - name: Compile backend
        working-directory: back
        run: mvn clean verify

      - name: SonarCloud analyse backend
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: back
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  sonar-front:
    name: frontend
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install & test frontend
        working-directory: front
        run: |
          npm ci
          npm run test -- --watch=false --browsers=CIChrome --code-coverage

      - name: Analyse SonarCloud frontend
        uses: SonarSource/sonarcloud-github-action@v2
        with:
          projectBaseDir: front
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
